name: Deploy blog

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"

      - name: Install and Build
        run: |
          yarn install
          yarn docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: blog
          FOLDER: src/.vuepress/dist

  deploy-server:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout Blog
        uses: actions/checkout@v3
        with:
          ref: blog
          fetch-depth: 0

      - name: Upload to Deploy Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: './*'
          target: '/www/wwwroot/yaien'
          overwrite: true
