name: Auto Deploy
on:
  push:
    branches:
      - master # 只要push到main分支，就会触发后续流程
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Github官方发布的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 在工作流中安装node环境
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 指定node版本

      # 编译
      - name: Build
        run: npm install && npm run docs:build

      # 部署到 Github Pages
      - name: Deploy Github
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: blog
          FOLDER: src/.vuepress/dist

      # 部署到云服务器
      - name: Deploy Service
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          # 引用配置，SSH私钥
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          # rsync参数，排除.pyc文件
          ARGS: -avz --delete --exclude='*.pyc'
          # 要推送的文件夹，路径相对于代码仓库的根目录
          FOLDER: src/.vuepress/dist
          # 引用配置，服务器端口
          SERVER_PORT: ${{ secrets.SSH_PORT }}
          # 引用配置，服务器的host名（IP或者域名domain.com）
          SERVER_IP: ${{ secrets.SSH_HOST }}
          # 引用配置，服务器登录名
          USERNAME: ${{ secrets.SSH_USERNAME }}
          # 部署到目标文件夹
          SERVER_DESTINATION: /usr/local/html/
