name: Auto Deploy
on:
  push:
    branches:
      - master # 只要push到main分支，就会触发后续流程
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Github官方发布的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 在工作流中安装node环境
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 指定node版本

      # 缓存Node.js的模块
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm  # npm caches files in ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      # 编译
      - name: Build Blog
        run: npm install && npm run docs:build

      # 部署到 Github Pages
      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: blog
          FOLDER: src/.vuepress/dist
          
      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Deploy to Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            rsync -avz --delete src/.vuepress/dist/ /usr/local/html/dist/

      # 静态文件上传到云服务器
#      - name: Deploy to Service
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.DEPLOY_KEY }}
#          source: "src/.vuepress/dist/*"
#          target: "/usr/local/html/dist/"
