name: Auto Deploy
on:
  push:
    branches:
      - master # 只要push到main分支，就会触发后续流程
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Github官方发布的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 在工作流中安装node环境
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 指定node版本

      # 编译
      - name: Build
        run: npm install && npm run docs:build

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: blog
          FOLDER: src/.vuepress/dist
